### ISSUE TITLE
请问木有使用文档？

### ISSUE THREAD

**Issue by jackie19** [TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin#6]

**Comment by xhrwang** [comment]
该 Plugin 是遵循标准 Cordova Plugin 的规范，可以在 Cordova 或者同源的 PhoneGap 开发环境中使用 README.md 中的命令进行集成。
另外，对于 Android 和 iOS 平台的 Demo，请见：
https://github.com/TalkingData/TalkingData-SDK-Cordova-Android-Demo
https://github.com/TalkingData/TalkingData-SDK-Cordova-iOS-Demo
