### ISSUE TITLE
trackPageBegin、trackPageEnd函数不存在

### ISSUE THREAD

**Issue by woaiso** [TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin#7]
//在进入页面时调用
TalkingData.trackPageBegin("page_name");
//在离开页面时调用
TalkingData.trackPageEnd("page_name");

**Comment by xhrwang** [comment]
你好，Javascript 接口定义为：

**Comment by xhrwang** [comment]
你好，Javascript 接口定义为：

**Comment by xhrwang** [comment]
你好，Javascript 接口定义为：

// 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 trackPageEnd 配合使用
    // pageName  : 页面自定义名称
    onPageBegin:function(pageName) {
        cordova.exec(null, null, "TalkingData", "onPageBegin", [pageName]);
    },

    // 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 trackPageBegin 配合使用
    // pageName  : 页面自定义名称
    onPageEnd:function(pageName) {
        cordova.exec(null, null, "TalkingData", "onPageEnd", [pageName]);
    },

**Comment by xhrwang** [comment]
你好，Javascript 接口定义为：

// 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 trackPageEnd 配合使用
// pageName : 页面自定义名称
onPageBegin:function(pageName) {
cordova.exec(null, null, "TalkingData", "onPageBegin", [pageName]);
},

// 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 trackPageBegin 配合使用
// pageName  : 页面自定义名称
onPageEnd:function(pageName) {
    cordova.exec(null, null, "TalkingData", "onPageEnd", [pageName]);
},

**Comment by xhrwang** [comment]
谢谢你的反馈，Javascript 代码中的 Comments 已经更新：

    // 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 onPageEnd 配合使用
    // pageName  : 页面自定义名称
    onPageBegin:function(pageName) {
        cordova.exec(null, null, "TalkingData", "onPageBegin", [pageName]);
    },

    // 触发页面事件，在页面加载完毕的时候调用，用于记录页面名称和使用时长，和 onPageBegin 配合使用
    // pageName  : 页面自定义名称
    onPageEnd:function(pageName) {
        cordova.exec(null, null, "TalkingData", "onPageEnd", [pageName]);
    },

**Comment by xhrwang** [comment]
close this issue for now.
